### ISSUE TITLE
FR: test data for ATAC

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/seq2science#345]
I've been placing this at the bottom of my TODO list for waaaaay too long now. After migration is done this should be a top priority.

@siebrenf you'll be happy with this :)

**Comment by siebrenf** [comment]
We've been using a very small subset of RNA-seq data for our tests. Rule blind_clustering, and now also deeptools bamCoverage (with the BPM normalization and strand filtering in RNA-seq), aren't working properly due to their size.

Unless the unit tests from #545 make these tests obsolete, RNA-seq is also in need of better test data.
