### ISSUE TITLE
samtools sort

### ISSUE THREAD

**Issue by simonvh** [vanheeringen-lab/seq2science#404]
https://github.com/vanheeringen-lab/seq2science/blob/cf045b357f8d41b40d1579603bebffd51fba3152/seq2science/rules/alignment.smk#L302

Have you tried / benchmarked setting larger memory for `samtools sort` (`-m 4G`)? With the defautl settings `samtools sort` generates *many* small files for sorting. I think this can slow down the process. An alternative is also `sambamba` which seems to sort faster (at least, the last time I looked at it).

**Comment by Maarten-vd-Sande** [comment]
Yes I am aware. However I think the issue is that some assemblies consist of many many many contigs, and that blows up in memory. But that is from memory ( +/- a year ago). I will leave this open, and test again.

You can already use sambamba as a sorter, but ... ofcourse there are minor differences in the way they sort. Samtools & sambamba sort slightly different on read names (not coordinates, and not sure anymore on what, but think about order of capital letters), which makes some tools very unhappy.

So I decided that every downstream tool MUST use the samtools-coordinate sorted bam, since I never had troubles with those. If you only do alignment, then you can choose the sort_order (coordinate/queryname) and sorter (samtools/sambamba).

**Comment by Maarten-vd-Sande** [comment]
https://vanheeringen-lab.github.io/seq2science/content/schemas.html#alignment-workflow-specific

**Comment by simonvh** [comment]
Ah, sounds reasonable. I suspected there might be a good reason. In any case, it might be good to have the `-m` option of samtools configurable.

**Comment by Maarten-vd-Sande** [comment]
Note for instance that genrich specifically uses [sambamba-queryname sorted bams](https://github.com/vanheeringen-lab/seq2science/blob/master/seq2science/rules/peak_calling.smk#L19), this is because it explodes when you give it samtools-queryname sorted bams. This means that during some workflows two versions of the same bam exist, but they differ just by sorters/sort orders. See for instance: https://github.com/biod/sambamba/issues/132.

> Ah, sounds reasonable. I suspected there might be a good reason. In any case, it might be good to have the -m option of samtools configurable.

Yes, will do
