### ISSUE TITLE
FR: Differential peaks

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/seq2science#566]
**Is your feature request related to a problem? Please describe.**
RNA-seq has DEseq2. Would be really nice if we re-use parts of that to use in either diffbind or DEseq2 itself.
https://support.bioconductor.org/p/132840/

If/when/once this is supported, it allows for immediate fluff heatmap and gimme maelstrom runs. Making the ATAC/ChIP pipelines truely end-to-end.

**Comment by JGASmits** [comment]
I think one problem might be that in order to run deseq you would also need to tell it the design formula & sample file. I know Siebren has implemented this for RNAseq, but personally I always struggled with putting this also in the config instead of running it in R (and only use the pipeline for the pre-processing).
Especially when performin time-course/ multiple comparisons I think its rather tricky sometimes. But then agian the nice thing would be that all would be streamlined in a single pipeline for the people that would use it.

**Comment by Maarten-vd-Sande** [comment]
That's good feedback. I haven't worked with DESeq in s2s, but I guess (hope) that with maybe better documentation, examples, and error messages this can be made easier? For me what would make it attractive is that we would be able to add gimmemotifs and fluff (and whatnot), so you do not have to do anything yourself anymore :P

**Comment by JGASmits** [comment]
Stop trying to completely automate my job Maarten! 
 
No I agree, it would be really cool if it automatically would run fluff & Maelstrom for example on differential peaks. :)
Perhaps its also a matter of me being to stubborn never to really get into how to use the RNAseq design part (since for me for the RNAseq it didnt make any sense). 

Since I'm rerunning some stuff with the genome with no haploid patches, ill see if i can figure out the design formula for RNA seq. Implementing Deseq on chipseq counts should be rather straightforward (I do it in a small R script from my jupyter notebook all the time).

**Comment by Maarten-vd-Sande** [comment]
Bonus points if it works with any of the pre-normalized tables (see biostars above). If you need help with the R part, @siebrenf is probably happy to help :angel: . All the other stuff I will help you with pleasure :smile:

**Comment by JGASmits** [comment]
Deseq2 only works with the pre-normalized tables!
I'll poke arround with it to see if i can get something a bit functional for simple comparisons.

**Comment by siebrenf** [comment]
Its the holidays stalebot, shoo!

**Comment by Maarten-vd-Sande** [comment]
:christmas_tree: :santa:

**Comment by siebrenf** [comment]
I'll have a look at implementing DESeq2. Judging by the amount of smileys, Maarten would like you to look ath this too Jos :p

> 
> 
> Deseq2 only works with the pre-normalized tables!
> I'll poke arround with it to see if i can get something a bit functional for simple comparisons.

**Comment by Maarten-vd-Sande** [comment]
All aboard the deseq2 train :steam_locomotive: 

![](https://media2.giphy.com/media/l2JJyDYEX1tXFmCd2/giphy.gif?cid=ecf05e47intl0xsmt22bsi2kp8lnsiucm9eol3kq30f1u74p&rid=giphy.gif)

**Comment by JGASmits** [comment]
Hahaha, this is still on my to-do but was continuously being bumped down by other stuff. 

> I'll have a look at implementing DESeq2. Judging by the amount of smileys, Maarten would like you to look ath this too Jos :p
> 
> >

**Comment by Maarten-vd-Sande** [comment]
> Deseq2 only works with the pre-normalized tables!

http://www.bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#input-data

>The values in the matrix should be un-normalized counts or estimated counts of sequencing reads

I guess it needs the _raw_ counts then?
