### ISSUE TITLE
FR: Better ChIP-seq bigWigs

### ISSUE THREAD

**Issue by simonvh** [vanheeringen-lab/seq2science#571]
**Is your feature request related to a problem? Please describe.**

Running bamCoverage with default settings will generate suboptimal bigWigs.

**Describe the solution you'd like**

* Estimate ChIP-seq fragment size (https://github.com/kundajelab/phantompeakqualtools, maybe there is a better option now).
* Use that fragment size with the `--extendReads, -e` of `bamCoverage`.

**(optional) Additional context**

The bigWigs for ChIP will be much improved!

![image](https://user-images.githubusercontent.com/281252/99493373-65258b00-296f-11eb-99b8-4319743d26b9.png)

**Comment by Maarten-vd-Sande** [comment]
I believe the bigwig that is visualized in the chip-seq pipeline is the `NAME_treat_pileup.bdg` from macs2. I believe that `phantompeakqualtools` is also a peak caller. We can just add it as a third optional peak caller (next to macs2 and genrich)?

Or are you running the alignment workflow and want to change how the bams are generated from there?

**Comment by simonvh** [comment]
No, the only change is the bigWig. I'm not sure what macs2 does, but the reads should be extended to the estimated fragment size before creating the bedgraph / bigwig. For paired-end, I think that macs uses the fragment, but for single end I'm not sure.

Phantompeakqualtools uses the peak caller spp, but it is not a peak caller. It generates quality statistics. Historically, the fragment size estimated by this tool is much more accurate than the size from macs2.

Finally, the bigwigs should be normalized. This is something that bamCoverage can do, but I'm not sure the macs2 pileup will do so?

**Comment by simonvh** [comment]
See https://groups.google.com/d/msg/macs-announcement/XawMJuBLYrc/ErL5oWVUWdYJ

But this is very old info, macs2 may be better by now?

**Comment by Maarten-vd-Sande** [comment]
I am not sure with macs2, since their docs are quite minimal. My guess would be that it visualizes sort-of the pileup (including model shift etc). This is because for atac we use `--nomodel shift extend etc` and the visualization is different depending on the settings, so my guess would be that it includes the chip fragment size shift. The google group is still talking about macs1, no clue how well that translates to macs2.

Maybe you can try with the bam from a chip workflow and use phantompeakqualtools & bamcoverage and see if it indeed is a different / better visualization? :innocent:

**Comment by simonvh** [comment]
You're right. It already looks good, forget about this issue :)
