### ISSUE TITLE
BUG: unwanted # character in config.yaml

### ISSUE THREAD

**Issue by Roel-Wester** [vanheeringen-lab/seq2science#718]
I ran an rna-seq workflow and found that my samples.tsv got overwritten and seq2science didn't use the fastq files that I had provided it with. I found out the config.yaml file generated after running seq2sience init rna-seq conatined a '#' character in the line specifying the fasq_dir. Removing this # seems to fix the issue, but maybe others have the same issue. 

![screenshot_seq2science](https://user-images.githubusercontent.com/85492803/121009754-d3f3f580-c794-11eb-9d4f-7f1a5d194957.PNG)

**Comment by siebrenf** [comment]
Hey Roel,

If I got it correctly you have three problems: 1) your samples.tsv was overwritten, 2) your local fastqs weren't used, and 3) this was because of the `#` in front of the `fastq_dir`.

1
Running `seq2sience init rna-seq` will create a `samples.tsv` and `config.yaml` in your current directory. If either of those already exist, it asks if you wish to overwrite them.
If either file was overwritten without asking, you were either using the `--force` flag, or your installation was corrupt!

2
If you want to quickly check what seq2science will do, you can make a dryrun (e.g. `seq2science run rna-seq --dryrun`). This will produce a DAG with rule names (and how often they run), and you can even see the in- and output of each individual rule. 

3
The `#` in front of `fastq_dir` was intentional (as the directory is automatically generated for public data), but is clearly confusing. Should we just remove the `#`, or should we change this line into something like `# some other directories: fastq_dir, counts_dir, deseq_dir`?

**Comment by Roel-Wester** [comment]
Hey Siebren,

Thanks for answering. 

So I specified not to overwrite them, but after running the workflow, my samples.tsv had been altered to only contain a few public datastets. I figured this was because it used different fastq files than the ones I wanted it to use, so that makes sense. For the last point, I guess I just didn't understand correctly then, it makes sense if you want to use public data, so I don't think a change is necessary. Maybe the docs can explain that you need to alter this for local data? Or contain some other, more elegant fix, that would clear things up imo. 

Thanks for the help!
